### ISSUE TITLE
Please update to the latest Coffeescript dependency

### ISSUE THREAD

**Issue by carboniris** [peerlibrary/meteor-data-lookup#1] opened 2017-12-03 23:24 UTC
For users who want to write a Meteor application in Coffeescript, this package as a direct or indirect dependency forces the use of Coffeescript 1. CoffeeScript 2.0.3_1 is the most recent version and should be preferred.

**Comment by mitar** [comment] 2018-01-10 08:53
As I see, CoffeeScript 2 is not yet released as part of Meteor release? It seems I have to wait for 1.6.1 for that and only then I will be able to publish a package? It seems release will be soon and I will do that then.

Thanks for bringing it to my attention.

**Closed as completed by mitar** 2018-01-10 08:53 UTC

**Comment by carboniris** [comment] 2018-01-11 07:41
The current version of coffeescript on Atmosphere is [2.0.3_1](https://atmospherejs.com/meteor/coffeescript). The most recent release of Meteor was [1.6.0.1](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.6.0.1), which occurred in December 2017, after November 2017 when the [commit](https://github.com/meteor/meteor/pull/9420/files) which updated the official meteor/coffeescript package to its current version. Running `meteor add coffeescript` in a meteor project directory as of right now will pull 2.0.3_1, there's no need to wait for a new Meteor release. Updating the package should only take a few minutes, all that's required is to update the version number in package.js and run `meteor update --all-packages && meteor publish peerlibrary:meteor-data-lookup`.

**Comment by mitar** [comment] 2018-01-11 08:11
Yes. I realized later and starting porting my packages. I really hate that Meteor requires that, but that's how it is. The issue is that I almost immediately got stuck with this bug: https://github.com/meteor/meteor/issues/9528 (So CoffeeScript 2 is sadly not backwards compatible with CoffeeScript 1 and requires packages to be really ported.)

If you could investigate it it would be of tremendous help.

**Comment by mitar** [comment] 2018-01-15 09:40
A new version with CoffeeScript 2 released.
